source 'https://cdn.cocoapods.org/'

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'OpenKuiklyIOSRender' , '~> 2.7.0'
  pod 'shared', :path => '../shared'
  pod 'KuiklyAudio', :path => '../KuiklyAudioIOS'

  pod 'SDWebImage'
end